### ISSUE TITLE
建议增加断线自动重连、自动打通指定隧道和指定网络连接后自启功能

### ISSUE THREAD

**Issue by tcjj3** [switch-iot/n2n_vLTS#10]
建议增加断线自动重连、自动打通指定隧道和指定网络（WIFI、流量或指定的WIFI）连接后自动启动的功能。
断线重连功能主要针对节点网络波动或者supernode不稳定导致连接断开的情况。
另外，建议增加自动打通指定隧道功能。具体情况是，新节点每次连接进n2n网络时，第一次与其中的某节点通信，打通隧道总是需要等待一定的时间，而打通后就不用再等待了，所以最好能根据事先的设定，让APP在连接n2n网络后，自动打通指定的一些节点的隧道（比如用ping的方式向节点发送数据），这样使用体验会好很多。

**Comment by switch-st** [comment]
- 断线重连功能现在是有的，会自动重连supernode，与对端edge节点不会自动重连。
- 指定隧道功能暂时不考虑。这个功能对n2n协议有比较大的改动，可能会引起不兼容的问题；而且保存的隧道信息并不一定管用，保存隧道就是保存两个edge彼此的外网IP端口信息，下次链接对端edge时，对端的外网IP端口可能已经变化了。

**Comment by gzz2000** [comment]
> * 断线重连功能现在是有的，会自动重连supernode，与对端edge节点不会自动重连。
> * 指定隧道功能暂时不考虑。这个功能对n2n协议有比较大的改动，可能会引起不兼容的问题；而且保存的隧道信息并不一定管用，保存隧道就是保存两个edge彼此的外网IP端口信息，下次链接对端edge时，对端的外网IP端口可能已经变化了。

我在使用中有发现，一段时间过后，和对端edge节点就从原来的p2p直连退回到通过supernode转发了，网络环境都没有变，是否是因为与对端edge断掉以后不会自动重新尝试建立p2p连接？我目前只能需要建立p2p连接的时候强制结束掉hin2n重新打开

**Comment by lucktu** [comment]
试试最新的吧，如果还有问题，请重新开一个pull
