### ISSUE TITLE
Add routes feature

### ISSUE THREAD

**Issue by Krush206** [switch-iot/n2n_vLTS#11]
Is there a way to add routes other than the one automatically provided by the choosen IP address?

**Comment by emanuele-f** [comment]
For the default gateway please check out #13 . For other routes, the routing mechanism should be implemented into n2n (e.g. https://github.com/switch-iot/n2n_ntop/pull/4/files#diff-6dd127424612a99b5f9eb1d1afe7c59aR1118) as the android vpn service does not implement a "add x via y" feature but only a "route x via the vpn software"

**Comment by emanuele-f** [comment]
Let's continue this feature request in #9

**Comment by Krush206** [comment]
I meant as in the latter case (route X via VPN), @emanuele-f. I know the Android VPN manager allows for multiple forwarding routes, but Hin2n didn't have such a feature by the time this issue was posted.

If this isn't a feature yet, I can take the time to implement.
