### ISSUE TITLE
Add ability to delete a Setting

### ISSUE THREAD

**Issue by emanuele-f** [switch-iot/n2n_vLTS#15]
Right now is only possible to add a new Setting

**Comment by lucktu** [comment]
It can be deleted, hold down a setting, slide to the left to see the delete button.
![image](https://github.com/lucktu/other/raw/master/image/speed/19072601.jpg)

**Comment by emanuele-f** [comment]
It's working, thank you. However, I would never have found it without your help, so I suggest to make it more visible for the users

**Comment by lucktu** [comment]
Yeah, we talked about it when he designed it. Maybe the author wants to give us a chance to hunt for treasure ^_^.
