### ISSUE TITLE
gradlew assemble 报错，找不到src/main/cpp/slog/slog.c，如下：

### ISSUE THREAD

**Issue by littlewangxiaobai** [switch-iot/n2n_vLTS#20]
CMake Error at D:\workspace\vpns\1\hin2n\Hin2n_android\app\CMakeLists.txt:105 (add_library):
  Cannot find source file:

    src/main/cpp/slog/slog.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

gradle：4.6

**Comment by liuping1234** [comment]
请问这问题解决了吗？我编译的时候也出现这情况了。

**Comment by emanuele-f** [comment]
@littlewangxiaobai did you solve the issue? Double check that `src/main/cpp/slog/slog.c` actually exists as this error usually occurs when the file is missing

**Comment by emanuele-f** [comment]
Closing as no feedback has been received. A simple way to compile hin2n is via Android Studio, as explained in https://github.com/switch-iot/hin2n#hin2n
