### ISSUE TITLE
Some suggestions for hin2n_v0.6.0-rc3

### ISSUE THREAD

**Issue by lucktu** [switch-iot/n2n_vLTS#30]
1. Name: it is recommended to have a default value, such as 2020070701, 2020070702

2. Recommended version number: v1/v2_2.6/v2_dev/v2_meyerd, when a version is selected, add a comment below indicating where it came from and the reference date. (for example, https://github.com/meyerd/n2n/tree/master/n2n_v1   Cited by 10 Oct 2017. Please do not use such marks: v1.0/v1.3.2/v2.5.0/v2.7.0, these figures are ambiguous)

3. Encryption: default twofish. the default is compatible with previous versions, so that unfamiliar people don't get it wrong and can connect to other devices

4. It is recommended that all items have a default value to guide the user to write correctly ( if not, give an example in title). for example, supernode, 1.2.3.4:10086 (Gateway IP address: 192.168.2.0/24:10.0.0.1).

5. MTU: for meyerd's n2n, using 1400 would result in poor communication, and 1390 would not work either. the maximum I measured was 1387, while the official is 1290, which I found to be too small, is recommended at 1384.

Thank you all!

**Comment by emanuele-f** [comment]
I'm not 100% sure that the ntop dev protocol has not changed, I'd recommend AES anyway for the future

**Comment by lucktu** [comment]
In order to ensure that novices, especially those who are trying for the first time (poor computer literacy), can connect to other computers, I think the best encryption here is twofish by default. and the drop down menu doesn't look too good here. suggest putting it in more.

**Comment by lucktu** [comment]
@emanuele-f 
What is the function of DNS? it doesn't seem to be working.
Thank you!

**Comment by emanuele-f** [comment]
> @emanuele-f
> What is the function of DNS? it doesn't seem to be working.
> Thank you!

Sorry I missed this message. I think that the ability to set a custom DNS server could be useful for some users but it should be an "advanced" option.
