### ISSUE TITLE
不能使用DHCP

### ISSUE THREAD

**Issue by KsharpMoring** [switch-iot/n2n_vLTS#31]
首先，我参照一下两篇教程，在自己的vps上启动supernode和edge，然后部署DHCP服务。
http://www.lucktu.com/archives/786.html
https://bugxia.com/475.html

然后，在自己的PC上启动edge时，原本是通过 `-a <本机IP>` 参数指定虚拟LAN的IP地址
但是 -a 参数如果写成 `-a <dhcp:DHCP服务器IP>`，那么就可以通过vps上的DHCP服务自动获取IP
我在自己的PC上已经成功了（如图，我是用的是bug侠制作的n2n启动器，效果和命令行是一样的）
![image](https://user-images.githubusercontent.com/31263957/90311802-98e8b300-df31-11ea-99ee-3f8b31c976cd.png)
![image](https://user-images.githubusercontent.com/31263957/90311761-45766500-df31-11ea-8b8a-2b52e21b64bd.png)

但是我在Hin2n中使用相同的写法时会提示格式错误。。。
![image](https://user-images.githubusercontent.com/31263957/90311719-bb2e0100-df30-11ea-81ed-f98a8e629333.png)

我觉得，填在GUI里的东西，就是作为启动进程时的参数，所以从技术上讲，这么填其实可以使用DHCP，结果GUI强制格式检查导致不能这么填？
又或者是Hin2n里的edge在编译时阉割了DHCP，就算这么填也没用？

**Comment by lucktu** [comment]
应该是不支持吧，别折腾了，别要求太高
