### ISSUE TITLE
hin2n_v0.6.0-rc3 -- base on n2n 2.8 ?

### ISSUE THREAD

**Issue by tlsalex** [switch-iot/n2n_vLTS#32]
Hi man,

Could I know hin2n_v0.6.0-rc3 is base on n2n v2.8 or it will not be a problem to work with n2n v2.8.

**Comment by siskai** [comment]
I compiled it with v 2.8 and works very well.

**Comment by lucktu** [comment]
No, it's a code from 2020-7-3.
