### ISSUE TITLE
header encryption support

### ISSUE THREAD

**Issue by felix-git-hub** [switch-iot/n2n_vLTS#40]
n2n 2.8 introduced full header encryption (- H option), will hin2n add support for this feature?

_The header which contains some metadata like the virtual MAC address of the edge nodes, their IP address and the community name optionally can be encrypted applying -H on the edges._

**Comment by lucktu** [comment]
And -S, which is important, needs someone to provide the code, which I don't.

**Comment by lucktu** [comment]
Has now supported.
