### ISSUE TITLE
填写网关后网络不可用

### ISSUE THREAD

**Issue by RockJohnson503** [switch-iot/n2n_vLTS#43]
之前填写网关都能正常运行，最近用的时候发现app卡死了，关闭也得kill掉app才行，然后去掉网关后就可以使用

**Comment by RockJohnson503** [comment]
看了日志后发现是dns无法解析supernode的域名

**Comment by dwj0** [comment]
同样发现此问题。
另外，可否把网关改为自定义路由。如：
192.168.1.0/24 使用网关：172.16.1.1
192.168.2.0/24使用网关：172.16.1.2

**Comment by lucktu** [comment]
这个功能是 emanuele-f 先生开发的，他是看不懂你们说什么的。这里也问过，这个功网关不大好用，应该是设置了网关后，所有流量都走了网关那边了 #32 
所以，为了大家交流方便，建议今后尽量用英文，或者中英文表达。

**Comment by lucktu** [comment]
现在已经正常，请下载最新app
