### ISSUE TITLE
android29报错

### ISSUE THREAD

**Issue by zhaokeping** [switch-iot/n2n_vLTS#47]
android29，没法设置低版本，因为高版本访问文件系统需要用到android:requestLegacyExternalStorage="true"
JNI DETECTED ERROR IN APPLICATION: fid == null
 in call to GetStaticObjectField
 from com.xxx.model.EdgeStatus N2NService.getEdgeStatus()

**Comment by ozyb** [comment]
targetSdkVersion 28  和 高版本访问文件系统需要用到android:requestLegacyExternalStorage="true" 无关

**Comment by ozyb** [comment]
> android29，没法设置低版本，因为高版本访问文件系统需要用到android:requestLegacyExternalStorage="true"
> JNI DETECTED ERROR IN APPLICATION: fid == null
> in call to GetStaticObjectField
> from com.xxx.model.EdgeStatus N2NService.getEdgeStatus()

targetSdkVersion 28 和 高版本访问文件系统需要用到android:requestLegacyExternalStorage="true" 无关

**Comment by zhaokeping** [comment]
> > android29，没法设置低版本，因为高版本访问文件系统需要用到android：requestLegacyExternalStorage =“ true” 
> > JNI检测到应用程序错误：fid == null 
> > ，
> > 从com.xxx.model.EdgeStatus N2NService.getEdgeStatus（ ）
> 
> targetSdkVersion 28和高版本访问文件系统需要用到android：requestLegacyExternalStorage =“ true”无关

是的，我降到28了，还是报错，编译没问题，运行时vpn创建好后就闪退，分析不出 原因

**Comment by ozyb** [comment]
> > > android29，没法设置低版本，因为高版本访问文件系统需要用到android：requestLegacyExternalStorage =“ true”
> > > JNI检测到应用程序错误：fid == null
> > > ，
> > > 从com.xxx.model.EdgeStatus N2NService.getEdgeStatus（ ）
> > 
> > 
> > targetSdkVersion 28和高版本访问文件系统需要用到android：requestLegacyExternalStorage =“ true”无关
> 
> 是的，我降到28了，还是报错，编译没问题，运行时vpn创建好后就闪退，分析不出 原因

断点调试一下
