### ISSUE TITLE
Hin2n not working!

### ISSUE THREAD

**Issue by mahdi-nasehiyan** [switch-iot/n2n_vLTS#5]
Hello i'm using this app on my Huawei Honor 4x running android 6 marshmallow.
i tried v0.5.2 and it did not work! then tried v0.6.0 and nothing changed...
i compiled 'supernode' for my windows 10 computer using vs2013 and i can connect using Edge GUI.
also i connect with the 'edgenode' that i compiled on several linux systems that i have( such as ubuntu kali and raspbian[raspberry pi] ) and they all work fine!
when i connect with Hin2n app a 'key icon' shows up on the notification bar(saying that a vpn is connected).
then, i can ping the ip that i set for my phone from an app on the phone it self and the ping response time is under 1ms !
but i can not ping my phone from any other edgenodes that are connected ...
any idea what is the problem?

**Comment by switch-st** [comment]
Are you using the correct version of n2n? Now Hin2n only supports [meyerd's version of n2n](https://github.com/meyerd/n2n).

**Comment by mahdi-nasehiyan** [comment]
No I'm not;(
So meyerd has two versions of n2n, which one should I compile and use?

**Comment by switch-st** [comment]
> No I'm not;(
> So meyerd has two versions of n2n, which one should I compile and use?

https://github.com/meyerd/n2n/tree/master/n2n_v2

**Comment by mahdi-nasehiyan** [comment]
sorry but i have a really stupid problem.
i compiled ntop's n2n on my raspbian (using make and make install)
and now i want to uninstall that version and install meyerd's version. so have should i uninstall it?
usually the command 'make uninstall' should do it but i tried that and it says:
`make: *** No rule to make target 'uninstall'.  Stop.`

so what should i do?

**Comment by mahdi-nasehiyan** [comment]
so i think i figured it out!
i just normally installed the meyerd's version and it replaced the old n2n.
[when i enter `edge -h` says built on Aug 28 which is today!]

then i tested Hin2n and it worked!

**Comment by switch-st** [comment]
Thank you for using this app.
