### ISSUE TITLE
Protocol version 2 not working

### ISSUE THREAD

**Issue by mrbluecoat** [switch-iot/n2n_vLTS#50]
Your ReadMe says:
> Hin2n now supports all v1/v2/v2s protocols

but I installed https://github.com/switch-iot/hin2n/releases/download/hin2n_v0.6.0-rc8_debug-7-gc2c9a59/hin2n_v0.6.0-rc8_debug-7-normal_allarch.apk on my Android 11 phone and the only protocol version that connected was v1.

v2 and v3 gave errors like:
```
07/Jun/2021 19:12:04 [supernode.c: 325] WARNING: Received packet with unknown protocol version (2): discarded
07/Jun/2021 19:12:07 [supernode.c: 317] WARNING: Received packet too short [len=34]
07/Jun/2021 19:12:08 [      n2n.c: 560] WARNING: Receive error [Success] or pkt too short [len=32]
07/Jun/2021 19:16:16 [supernode.c: 325] WARNING: Received packet with unknown protocol version (3): discarded
```

v2s gave a GUI error in the mobile app and once crashed it.

Supernode info:
```
Welcome to n2n v.1.3.2 for x86_64
Built on 04/17/18 07:52:27 AM
```

**Comment by galaxyskyknight** [comment]
most likely mtu issue.

**Comment by lucktu** [comment]
Please try the latest one
