### ISSUE TITLE
No new release any more?

### ISSUE THREAD

**Issue by galaxyskyknight** [switch-iot/n2n_vLTS#53]
I am looking forward to there is a new release that support add multiple CIDR:gateway entry, the current gateway option works too weak in feature wise and cannot handle multiple LAN interconnection.... is there anyone WIP?

**Comment by siskai** [comment]
I created PR that supports n2n v3 stable and full header encryption.

Maybe this will help you.

**Comment by GreatMichaelLee** [comment]
> I created PR that supports n2n v3 stable and full header encryption.
> 
> Maybe this will help you.

Is it done? this project is far behind the n2n server side and seems nobody is working on it any more?

**Comment by lucktu** [comment]
Please try the latest one
