### ISSUE TITLE
Is there still anyone working on this project?

### ISSUE THREAD

**Issue by galaxyskyknight** [switch-iot/n2n_vLTS#59]
I am wondering this project is suspended? Looks like it is far behind the n2n server side development....

as there are N2N3.0 released and there are two important features for me:

1) Federation feature and header encryption and supernode selection via --select-mac
2) static routing parameter using -n CIDR to specify the route

Can anyone help to integrate those features to this Android project? It is highly appericiated. thanks!

**Comment by lucktu** [comment]
"Federation feature and header encryption and supernode selection via --select-mac"
Federation is immature and unsupportive, header encryption has supported, 

Now maintenance personnel is relatively few, so some not commonly used function, forgive me. 

And we welcome your help in perfecting.

Thank you for your feedback.
