### ISSUE TITLE
Problems building with Android Studio on Windows

### ISSUE THREAD

**Issue by aphilsmith** [switch-iot/n2n_vLTS#6]
1.  Ran
git clone https://github.com/switch-iot/n2n_vLTS.git --recurse-submodules
2. Executed link.bat 
3. Launched Android Studio IDE with NDK and CMake components.
4. From the IDE Terminal, ran gradlew.bat build

Auto configuration in gradle completes, but CMake fails to find many source files that are, in fact there, and gives "could not determine linker language" errors on folder symlinks.

How is this project built???

**Comment by switch-st** [comment]
Try this command and build again.
git clone -c core.symlinks=true https://github.com/switch-iot/hin2n.git --recurse-submodules && cd hin2n && link.bat

**Comment by aphilsmith** [comment]
OK, but after I do this, can I run the gradlew.bat in the IDE Terminal
window, or must I do some other setup?

**Comment by switch-st** [comment]
> OK, but after I do this, can I run the gradlew.bat in the IDE Terminal window, or must I do some other setup?

Just run `gradlew.bat assembleDebug` or `gradlew.bat assembleGithubAllarchDebug` is fine.

**Comment by aphilsmith** [comment]
After the above commands, I did a gradle project import from the Android
Studio IDE and got this error

**Comment by aphilsmith** [comment]
Error while executing process
C:\Users\aphil\AppData\Local\Android\sdk\cmake\3.6.4111459\bin\cmake.exe
with arguments
{-HC:\Users\aphil\Downloads\switch-iot\hin2n\Hin2n_android\app
-BC:\Users\aphil\Downloads\switch-iot\hin2n\Hin2n_android\app\.externalNativeBuild\cmake\buglyAllarchRelease\x86_64
-DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-16
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\aphil\Downloads\switch-iot\hin2n\Hin2n_android\app\build\intermediates\cmake\buglyAllarch\release\obj\x86_64
-DCMAKE_BUILD_TYPE=Release
-DANDROID_NDK=C:\Users\aphil\AppData\Local\Android\sdk\ndk-bundle
-DCMAKE_CXX_FLAGS=
-DCMAKE_TOOLCHAIN_FILE=C:\Users\aphil\AppData\Local\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake
-DCMAKE_MAKE_PROGRAM=C:\Users\aphil\AppData\Local\Android\sdk\cmake\3.6.4111459\bin\ninja.exe
-GAndroid Gradle - Ninja}

**Comment by aphilsmith** [comment]
Trying gradlew.bat assembleDebug in the IDE Terminal window....

**Comment by aphilsmith** [comment]
This worked. Thanks. I now need the gradlew.bat option  to build a Release,
and the location of the APK.

**Comment by switch-st** [comment]
gradlew.bat assembleRelease
Hin2n_android/app/build/outputs/apk/
