### ISSUE TITLE
hin2n_v1.0-rc1版本在华为手机下闪退

### ISSUE THREAD

**Issue by xuan880** [switch-iot/n2n_vLTS#61]
app版本是:hin2n_v1.0-rc1
手机型号:荣耀 V10
手机系统是:harmonyos 2.0.0.230
问题表现:app打开先是一片白,然后直接退出.
其他信息:在我的另外一台mate40中有同样的问题.
相关日志:
130|HWBKL:/ $ logcat --pid=12846                                                                                                 
--------- beginning of system
05-19 23:55:04.098 12846 12846 D ActivityThread: Attach thread to application
05-19 23:55:04.117 12846 12868 I HwActivityThreadImpl: mSocketName: 03216872-5607-42b8-9b78-be886b787506
05-19 23:55:04.117 12846 12868 I HwActivityThreadImpl: initPreloadedSocked end mPreloadStatus 2
05-19 23:55:04.119 12846 12868 I HwActivityThreadImpl: before connect app.socketName:03216872-5607-42b8-9b78-be886b787506
05-19 23:55:04.128 12846 12846 W ActivityThread: Application wang.switchy.hin2n can be debugged on port 8100...
05-19 23:55:04.134 12846 12869 I ActivityThread: Init compatible state: true
05-19 23:55:04.268 12846 12846 I HwActivityThreadImpl: accept socket mSocketName: 03216872-5607-42b8-9b78-be886b787506
05-19 23:55:04.268 12846 12846 I HwActivityThreadImpl: accept socket end
05-19 23:55:04.268 12846 12868 I HwActivityThreadImpl: connectContinuePreload end mPreloadStatus 3
05-19 23:55:04.268 12846 12846 I HwActivityThreadImpl: acceptPreloadedApplication end mPreloadStatus 3
05-19 23:55:04.462 12846 12846 I ActivityThread: finishPreloaded preloadStatus 3
05-19 23:55:04.462 12846 12846 I ActivityThread: finishPreloaded end preloadStatus 3
05-19 23:55:04.463 12846 12846 I RtgSchedEvent: current pid:12846 AppType:-1
05-19 23:55:04.517 12846 12846 V ActivityThread: callActivityOnCreate
05-19 23:55:04.694 12846 12846 D ActivityThread: add activity client record, r= ActivityRecord{f280194 token=android.os.BinderProxy@9367da5 {wang.switchy.hin2n/wang.switchy.hin2n.activity.MainActivity}} token= android.os.BinderProxy@9367da5
--------- beginning of crash
05-19 23:55:04.708 12846 12846 E AndroidRuntime: FATAL EXCEPTION: main
05-19 23:55:04.708 12846 12846 E AndroidRuntime: Process: wang.switchy.hin2n, PID: 12846
05-19 23:55:04.708 12846 12846 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {wang.switchy.hin2n/wang.switchy.hin2n.activity.MainActivity}: android.database.sqlite.SQLiteException: no such column: T.HEADER_ENC (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT T."_id",T."VERSION",T."NAME",T."IP_MODE",T."IP",T."NETMASK",T."COMMUNITY",T."PASSWORD",T."DEV_DESC",T."SUPER_NODE",T."MORE_SETTINGS",T."SUPER_NODE_BACKUP",T."MAC_ADDR",T."MTU",T."LOCAL_IP",T."HOLE_PUNCH_INTERVAL",T."RESOVE_SUPERNODE_IP",T."LOCAL_PORT",T."ALLOW_ROUTING",T."DROP_MUTICAST",T."USE_HTTP_TUNNEL",T."TRACE_LEVEL",T."IS_SELCECTED",T."GATEWAY_IP",T."DNS_SERVER",T."ENCRYPTION_MODE",T."HEADER_ENC" FROM "N2NSettingList" T WHERE T."_id"=?, (OS error - 2:No such file or directory)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5078)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5121)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:110)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
05-19 23:55:04.708 12846 12846 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: no such column: T.HEADER_ENC (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT T."_id",T."VERSION",T."NAME",T."IP_MODE",T."IP",T."NETMASK",T."COMMUNITY",T."PASSWORD",T."DEV_DESC",T."SUPER_NODE",T."MORE_SETTINGS",T."SUPER_NODE_BACKUP",T."MAC_ADDR",T."MTU",T."LOCAL_IP",T."HOLE_PUNCH_INTERVAL",T."RESOVE_SUPERNODE_IP",T."LOCAL_PORT",T."ALLOW_ROUTING",T."DROP_MUTICAST",T."USE_HTTP_TUNNEL",T."TRACE_LEVEL",T."IS_SELCECTED",T."GATEWAY_IP",T."DNS_SERVER",T."ENCRYPTION_MODE",T."HEADER_ENC" FROM "N2NSettingList" T WHERE T."_id"=?, (OS error - 2:No such file or directory)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1030)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:637)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:610)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:66)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1482)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1416)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at org.greenrobot.greendao.database.StandardDatabase.rawQuery(StandardDatabase.java:32)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at org.greenrobot.greendao.AbstractDao.load(AbstractDao.java:147)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at wang.switchy.hin2n.activity.MainActivity.onResume(MainActivity.java:326)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1472)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:8351)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5068)
05-19 23:55:04.708 12846 12846 E AndroidRuntime:        ... 11 more

**Comment by tz527129804** [comment]
> app版本是:hin2n_v1.0-rc1 手机型号:荣耀 V10 手机系统是:harmonyos 2.0.0.230 问题表现:app打开先是一片白,然后直接退出. 其他信息:在我的另外一台mate40中有同样的问题. 相关日志: 130|HWBKL:/ $ logcat --pid=12846 --------- beginning of system 05-19 23:55:04.098 12846 12846 D ActivityThread: Attach thread to application 05-19 23:55:04.117 12846 12868 I HwActivityThreadImpl: mSocketName: 03216872-5607-42b8-9b78-be886b787506 05-19 23:55:04.117 12846 12868 I HwActivityThreadImpl: initPreloadedSocked end mPreloadStatus 2 05-19 23:55:04.119 12846 12868 I HwActivityThreadImpl: before connect app.socketName:03216872-5607-42b8-9b78-be886b787506 05-19 23:55:04.128 12846 12846 W ActivityThread: Application wang.switchy.hin2n can be debugged on port 8100... 05-19 23:55:04.134 12846 12869 I ActivityThread: Init compatible state: true 05-19 23:55:04.268 12846 12846 I HwActivityThreadImpl: accept socket mSocketName: 03216872-5607-42b8-9b78-be886b787506 05-19 23:55:04.268 12846 12846 I HwActivityThreadImpl: accept socket end 05-19 23:55:04.268 12846 12868 I HwActivityThreadImpl: connectContinuePreload end mPreloadStatus 3 05-19 23:55:04.268 12846 12846 I HwActivityThreadImpl: acceptPreloadedApplication end mPreloadStatus 3 05-19 23:55:04.462 12846 12846 I ActivityThread: finishPreloaded preloadStatus 3 05-19 23:55:04.462 12846 12846 I ActivityThread: finishPreloaded end preloadStatus 3 05-19 23:55:04.463 12846 12846 I RtgSchedEvent: current pid:12846 AppType:-1 05-19 23:55:04.517 12846 12846 V ActivityThread: callActivityOnCreate 05-19 23:55:04.694 12846 12846 D ActivityThread: add activity client record, r= ActivityRecord{f280194 token=android.os.BinderProxy@9367da5 {wang.switchy.hin2n/wang.switchy.hin2n.activity.MainActivity}} token= android.os.BinderProxy@9367da5 --------- beginning of crash 05-19 23:55:04.708 12846 12846 E AndroidRuntime: FATAL EXCEPTION: main 05-19 23:55:04.708 12846 12846 E AndroidRuntime: Process: wang.switchy.hin2n, PID: 12846 05-19 23:55:04.708 12846 12846 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {wang.switchy.hin2n/wang.switchy.hin2n.activity.MainActivity}: android.database.sqlite.SQLiteException: no such column: T.HEADER_ENC (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT T."_id",T."VERSION",T."NAME",T."IP_MODE",T."IP",T."NETMASK",T."COMMUNITY",T."PASSWORD",T."DEV_DESC",T."SUPER_NODE",T."MORE_SETTINGS",T."SUPER_NODE_BACKUP",T."MAC_ADDR",T."MTU",T."LOCAL_IP",T."HOLE_PUNCH_INTERVAL",T."RESOVE_SUPERNODE_IP",T."LOCAL_PORT",T."ALLOW_ROUTING",T."DROP_MUTICAST",T."USE_HTTP_TUNNEL",T."TRACE_LEVEL",T."IS_SELCECTED",T."GATEWAY_IP",T."DNS_SERVER",T."ENCRYPTION_MODE",T."HEADER_ENC" FROM "N2NSettingList" T WHERE T."_id"=?, (OS error - 2:No such file or directory) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5078) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5121) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:110) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.os.Looper.loop(Looper.java:219) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8668) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: no such column: T.HEADER_ENC (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT T."_id",T."VERSION",T."NAME",T."IP_MODE",T."IP",T."NETMASK",T."COMMUNITY",T."PASSWORD",T."DEV_DESC",T."SUPER_NODE",T."MORE_SETTINGS",T."SUPER_NODE_BACKUP",T."MAC_ADDR",T."MTU",T."LOCAL_IP",T."HOLE_PUNCH_INTERVAL",T."RESOVE_SUPERNODE_IP",T."LOCAL_PORT",T."ALLOW_ROUTING",T."DROP_MUTICAST",T."USE_HTTP_TUNNEL",T."TRACE_LEVEL",T."IS_SELCECTED",T."GATEWAY_IP",T."DNS_SERVER",T."ENCRYPTION_MODE",T."HEADER_ENC" FROM "N2NSettingList" T WHERE T."_id"=?, (OS error - 2:No such file or directory) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1030) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:637) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:610) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:66) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1482) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1416) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at org.greenrobot.greendao.database.StandardDatabase.rawQuery(StandardDatabase.java:32) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at org.greenrobot.greendao.AbstractDao.load(AbstractDao.java:147) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at wang.switchy.hin2n.activity.MainActivity.onResume(MainActivity.java:326) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1472) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.Activity.performResume(Activity.java:8351) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5068) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: ... 11 more

我的华为手机需要卸载老版本，再安装新版本才不会闪退，你可以试试。型号:nova8 系统:harmonyos 2.0.0.232  另外在我的matepad ro也是需要卸载原版本才行，不然也是闪退

**Comment by xuan880** [comment]
> > app版本是:hin2n_v1.0-rc1 手机型号:荣耀 V10 手机系统是:harmonyos 2.0.0.230 问题表现:app打开先是一片白,然后直接退出. 其他信息:在我的另外一台mate40中有同样的问题. 相关日志: 130|HWBKL:/ $ logcat --pid=12846 --------- beginning of system 05-19 23:55:04.098 12846 12846 D ActivityThread: Attach thread to application 05-19 23:55:04.117 12846 12868 I HwActivityThreadImpl: mSocketName: 03216872-5607-42b8-9b78-be886b787506 05-19 23:55:04.117 12846 12868 I HwActivityThreadImpl: initPreloadedSocked end mPreloadStatus 2 05-19 23:55:04.119 12846 12868 I HwActivityThreadImpl: before connect app.socketName:03216872-5607-42b8-9b78-be886b787506 05-19 23:55:04.128 12846 12846 W ActivityThread: Application wang.switchy.hin2n can be debugged on port 8100... 05-19 23:55:04.134 12846 12869 I ActivityThread: Init compatible state: true 05-19 23:55:04.268 12846 12846 I HwActivityThreadImpl: accept socket mSocketName: 03216872-5607-42b8-9b78-be886b787506 05-19 23:55:04.268 12846 12846 I HwActivityThreadImpl: accept socket end 05-19 23:55:04.268 12846 12868 I HwActivityThreadImpl: connectContinuePreload end mPreloadStatus 3 05-19 23:55:04.268 12846 12846 I HwActivityThreadImpl: acceptPreloadedApplication end mPreloadStatus 3 05-19 23:55:04.462 12846 12846 I ActivityThread: finishPreloaded preloadStatus 3 05-19 23:55:04.462 12846 12846 I ActivityThread: finishPreloaded end preloadStatus 3 05-19 23:55:04.463 12846 12846 I RtgSchedEvent: current pid:12846 AppType:-1 05-19 23:55:04.517 12846 12846 V ActivityThread: callActivityOnCreate 05-19 23:55:04.694 12846 12846 D ActivityThread: add activity client record, r= ActivityRecord{f280194 token=android.os.BinderProxy@9367da5 {wang.switchy.hin2n/wang.switchy.hin2n.activity.MainActivity}} token= android.os.BinderProxy@9367da5 --------- beginning of crash 05-19 23:55:04.708 12846 12846 E AndroidRuntime: FATAL EXCEPTION: main 05-19 23:55:04.708 12846 12846 E AndroidRuntime: Process: wang.switchy.hin2n, PID: 12846 05-19 23:55:04.708 12846 12846 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {wang.switchy.hin2n/wang.switchy.hin2n.activity.MainActivity}: android.database.sqlite.SQLiteException: no such column: T.HEADER_ENC (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT T."_id",T."VERSION",T."NAME",T."IP_MODE",T."IP",T."NETMASK",T."COMMUNITY",T."PASSWORD",T."DEV_DESC",T."SUPER_NODE",T."MORE_SETTINGS",T."SUPER_NODE_BACKUP",T."MAC_ADDR",T."MTU",T."LOCAL_IP",T."HOLE_PUNCH_INTERVAL",T."RESOVE_SUPERNODE_IP",T."LOCAL_PORT",T."ALLOW_ROUTING",T."DROP_MUTICAST",T."USE_HTTP_TUNNEL",T."TRACE_LEVEL",T."IS_SELCECTED",T."GATEWAY_IP",T."DNS_SERVER",T."ENCRYPTION_MODE",T."HEADER_ENC" FROM "N2NSettingList" T WHERE T."_id"=?, (OS error - 2:No such file or directory) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5078) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5121) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:110) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.os.Looper.loop(Looper.java:219) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8668) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: no such column: T.HEADER_ENC (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT T."_id",T."VERSION",T."NAME",T."IP_MODE",T."IP",T."NETMASK",T."COMMUNITY",T."PASSWORD",T."DEV_DESC",T."SUPER_NODE",T."MORE_SETTINGS",T."SUPER_NODE_BACKUP",T."MAC_ADDR",T."MTU",T."LOCAL_IP",T."HOLE_PUNCH_INTERVAL",T."RESOVE_SUPERNODE_IP",T."LOCAL_PORT",T."ALLOW_ROUTING",T."DROP_MUTICAST",T."USE_HTTP_TUNNEL",T."TRACE_LEVEL",T."IS_SELCECTED",T."GATEWAY_IP",T."DNS_SERVER",T."ENCRYPTION_MODE",T."HEADER_ENC" FROM "N2NSettingList" T WHERE T."_id"=?, (OS error - 2:No such file or directory) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1030) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:637) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:610) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:66) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1482) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1416) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at org.greenrobot.greendao.database.StandardDatabase.rawQuery(StandardDatabase.java:32) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at org.greenrobot.greendao.AbstractDao.load(AbstractDao.java:147) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at wang.switchy.hin2n.activity.MainActivity.onResume(MainActivity.java:326) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1472) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.Activity.performResume(Activity.java:8351) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5068) 05-19 23:55:04.708 12846 12846 E AndroidRuntime: ... 11 more
> 
> 我的华为手机需要卸载老版本，再安装新版本才不会闪退，你可以试试。型号:nova8 系统:harmonyos 2.0.0.232 另外在我的matepad ro也是需要卸载原版本才行，不然也是闪退

的确可以了,看来harmonyos系统都需要这样才能安装新版本.
