### ISSUE TITLE
如何在有root权限的情况下，使用n2n cli？

### ISSUE THREAD

**Issue by Lua12138** [switch-iot/n2n_vLTS#62]
# 环境/目的

- 拥有root权限
- 不需要UI
- 能够通过CLI启停

# 已经做过的尝试

- 通过NDK编译编译原版N2N
    - 其中做了一些修改
        - https://github.com/ntop/n2n/blob/cf23457d3b08db54a61b0c79649acc2d0a03027b/src/tuntap_linux.c#L109
        - 修改为`/dev/tun`
- 在目标设备（Android 10）上通过root运行
    - `edge -c my12138 -k mysecretpass -a 192.168.100.1 -f -l supernode.ntop.org:7777`
- 看起来一切正常，可是网络并不通

输出日志如下：

```
30/Jun/2022 03:43:56 [edge_utils.c:3168] adding supernode = supernode.ntop.org:7777
30/Jun/2022 03:43:56 [edge.c:1028] WARNING: switching to AES as key was provided
30/Jun/2022 03:43:56 [edge.c:1068] starting n2n edge 3.1.1-40-gcf23457-dirty Jun 30 2022 08:24:48
30/Jun/2022 03:43:56 [edge.c:1074] using compression: none.
30/Jun/2022 03:43:56 [edge.c:1075] using AES cipher.
30/Jun/2022 03:43:56 [edge_utils.c:392] number of supernodes in the list: 1
30/Jun/2022 03:43:56 [edge_utils.c:394] supernode 0 => supernode.ntop.org:7777
30/Jun/2022 03:43:56 [edge.c:1099] use manually set IP address
30/Jun/2022 03:43:56 [edge.c:1217] created local tap device IP: 192.168.100.1, Mask: 255.255.255.0, MAC: DE:3A:4E:84:91:B3
30/Jun/2022 03:43:56 [edge.c:1276] WARNING: n2n has not been compiled with libcap-dev; some commands may fail
30/Jun/2022 03:43:56 [edge.c:1282] dropping privileges to uid=9999, gid=9999
30/Jun/2022 03:43:56 [edge.c:1307] edge started
30/Jun/2022 03:43:56 [edge_utils.c:1160] successfully joined multicast group 224.0.0.68:1968
30/Jun/2022 03:44:00 [edge_utils.c:2527] [OK] edge <<< ================ >>> supernode
```
---

猜测原因可能是

- 原始的VpnService.protect并未调用，因此数据并未实际发送出去
- 路由表存在问题
    - 通过`ip route`查看系正常
- IFF_TAP失败
    - 但相关调用的ioctl并未返回失败

看起来更像是第一种情况，但是仍然不确定。

因此想咨询下各位大佬，当初开发这个项目的时候，应该是经历过一个阶段，在Android设备上，通过root可用，随后再实现的VpnService，以及在应用模拟的Tap设备。那么当初是如何让原版的n2n能够在root Android上直接运行的呢？

感谢各位大佬。

**Comment by lucktu** [comment]
抱歉，回答晚了。
这个问题我也不懂，switch.王 比较清楚，但他现在很少来这里，可能没法回复你。
好像是说，是你的网卡那里没有处理好。
在我的gihub上，也有一些之前他们编译的，你可以试试：https://github.com/lucktu/n2n

**Comment by Lua12138** [comment]
感谢 现在看起来更像是打开tun设备以后，所有流量都进入了tun，正常Android开发会需要将正常出口的流量通过VpnService#protect 使之能够不在进入tun导致回环。但是我搜了搜，似乎NDK中没有提供相关API
