### ISSUE TITLE
App的community的字符串长度无法设置大于15个字符

### ISSUE THREAD

**Issue by xjl456852** [switch-iot/n2n_vLTS#65]
你好,App的community的字符串长度无法设置大于15个字符
我是用community当做自己搭建服务器的密码,n2n官网也是这么建议的,我设置的community字符会大于15个字符.
windows电脑版的n2n是可以连接成功的,但是App版本无法保存大于15个字符才community.
希望这个功能可以改进一下,谢谢,非常感谢您的辛苦付出.
感谢.

**Comment by ozyb** [comment]
你的密码长度是多少？ 
n2n   #define N2N_COMMUNITY_SIZE   v1\v2都是16 ；v3是20

**Comment by xjl456852** [comment]
我用的v3版本,提示密码还是大于15个无法保存.我尝试把密码改成16个都不行.

**Comment by ozyb** [comment]
先不处理了。不建议community和密码一样。双重认证更安全。

**Comment by lucktu** [comment]
@xjl456852 已修复，虽然目前只支持20位，但我像其他系统上的一样，可以输入更多位，实际起作用的是前20位。

修改方法是由网友“Oliver0624”提供的，我只是代发。

**Comment by lucktu** [comment]
最后又改回支持20位了

**Comment by xjl456852** [comment]
> 最后又改回支持20位了

感谢感谢
