### ISSUE TITLE
Need help with p2p internet configuration

### ISSUE THREAD

**Issue by remixer-dec** [switch-iot/n2n_vLTS#67]
Hello! I am trying to forward all internet traffic from one android device to another, but not sure how to do it correctly.  I saw this functionality mentioned in #19 and #9 
On each device I added an edge node with specific IP (10.0.0.50 and 10.0.0.51), made sure that there are no connection issues and that I can ping one device from another.
I checked [enable packet forwarding] checkbox on both devices.
I added gateway IP 10.0.0.50 on a device with IP 10.0.0.51 and reconnected both devices
And after this change, device with IP 10.0.0.51 cannot ping any IP on the internet or access any external website
I tried both v2 and v3, different servers, but it seems like result is always the same - no connection. Am I doing something wrong?

**Comment by lucktu** [comment]
Your idea is dangerous in China, and n2n is very fragile.

**Comment by remixer-dec** [comment]
Not sure what do you mean 🤔 
Was this functionality removed?
Is it forbidden to disclose configuration details in the outside world?
