### ISSUE TITLE
最新的3.1提供了用户名密码登录的功能，您能否增加相关配置，或增加一个自定义命令配置的窗口呢

### ISSUE THREAD

**Issue by garfeng** [switch-iot/n2n_vLTS#70]
https://github.com/ntop/n2n/blob/dev/doc/Authentication.md

能否提供一个多行输入框，允许用户输入没列出的命令参数呢。

**Comment by lucktu** [comment]
因为每一个参数都需要底层代码的支持，而hin2n是将n2n的基层代码“翻译”/重写一遍来实现的，致命的是目前无人做此事。
