### ISSUE TITLE
安卓7以下疑似无法使用v3节点

### ISSUE THREAD

**Issue by asahiba** [switch-iot/n2n_vLTS#72]
连接V3时日志显示正常连接 可以被分配IP 但无法与其他设备建立连接

**Comment by ozyb** [comment]
可以提供一下连接的日志信息么。安卓7测试是正常的，没有更低版本的设备了

**Comment by asahiba** [comment]
> 可以提供一下连接的日志信息吗。安卓7测试是正常的，没有更低版本的设备了

![15e4b686545d8e26](https://user-images.githubusercontent.com/73240349/215793900-f2227050-2d36-4c0e-9561-e6163d8fd90d.jpg)这里提供临时找的一个
我可以肯定存在这个问题 因为我在教别人使用hin2n的过程中 遇到了接近10次配置正确却无法联机的情况 出问题的设备都是安卓7及以下的

**Comment by asahiba** [comment]
![Screenshot_2023-01-31-23-01-57-593_net he networktools](https://user-images.githubusercontent.com/73240349/215797002-157a04ab-0a97-41f9-8f61-9b27a418e004.jpg)
无法ping通 也无法进行其他连接

**Comment by asahiba** [comment]
ping测试是刚刚找人做的 所以IP不一致

**Comment by asahiba** [comment]
![-27248198d844ca9a](https://user-images.githubusercontent.com/73240349/215800099-453e1084-c5b8-46a8-94cd-00705adc32d4.jpg)
这是默认服务器的数据 依旧确认配置无误但仍无法连接

**Comment by asahiba** [comment]
并且这些设备在切换v2节点之后都可以正常连接

**Comment by lucktu** [comment]
外观上看不出来，貌似又是正常的，使用自己的中心节点，看上面有没有连接上去？还是会不会运行中丢了参数？

**Comment by asahiba** [comment]
> 外观上看不出来，貌似又是正常的，使用自己的中心节点，看上面有没有连接上去？还是会不会运行中丢了参数？

我提供的图片里也有使用官方默认节点的测试 依旧无法ping通

**Comment by asahiba** [comment]
> 行

自己的节点会有连接的反馈 因为开启了DHCP 要是没有连接上的话是不能被返回IP的

**Comment by asahiba** [comment]
目前无法提供服务端的日志 因为我没有安卓7的设备

**Comment by lucktu** [comment]
去群主的群里反馈吧
