### ISSUE TITLE
Add ability to tunnel specific networks

### ISSUE THREAD

**Issue by tcjj3** [switch-iot/n2n_vLTS#9]
建议增加自定义路由转发。原理是每次在创建VPNService时，用addDnsServer和addRoute方法，把自定义的DNS和路由信息参数加入进去，以达到配置自定义路由的效果（运行时修改自定义路由表的话，重新创建VPNService并重写新的参数即可）。因为实际使用中组网的目的不一定只是为了访问具体主机，在某些场合还有链路分流或者使用某一个节点的内网环境的需求。谢谢！

**Comment by switch-st** [comment]
下一步会支持该功能。之前研究过这个方法，加入addRoute后没起作用，怀疑是hin2n数据链路层实现的问题，我抽空抓包仔细看下。

**Comment by tcjj3** [comment]
查了一下资料，安卓的VPNService只是负责把nat转换后的数据包转发到tun0接口，没有为这个接口设定网关，所以转发到指定网关的部分应该是由应用层来完成的。

**Comment by switch-st** [comment]
:thumbsup: :thumbsup: 原来是这样，谢了，抽空研究下

**Comment by emanuele-f** [comment]
Please also note that you can use addRoute to forward all the internet traffic with this trick:

另请注意，您可以使用addRoute通过此技巧转发所有互联网流量：

sudo ip route add 0.0.0.0/1 via 10.0.0.50

(source https://github.com/zerotier/ZeroTierOne/issues/178#issuecomment-204599227)

**Comment by emanuele-f** [comment]
Please check out #13

**Comment by lucktu** [comment]
现在增加了一个 gateway ip address 的选项，可以试试是否达到了你所要求的效果。

**Comment by emanuele-f** [comment]
It would be useful to only route specific subnets via hin2n. E.g. if away from home/office, I want to reach the remote network without forwarding all the traffic through n2n (so the internet gateway remain unchanged).
